more checking

diff --git a/tpkg b/tpkg
--- a/tpkg
+++ b/tpkg
@@ -384,6 +384,11 @@ if [ $goal = "extract" ]; then
 fi
 
 # make a tmp dir during execution
+if [ "$goal" != "extract" ]; then
+        err "[fatal] What do you mean with $goal?. Abort"
+	cd $TPKG_CURRENT
+        exit 1
+fi
 
 dir=`mktemp -d "./$testname.XXXXXX"`
 if [ ! -d $dir ]; then 
