we can clone

diff --git a/tpkg b/tpkg
--- a/tpkg
+++ b/tpkg
@@ -84,7 +84,7 @@ function usage() {
         out "Reporting/Cleanup"
         out " report.:\tcreate a nice report from all the result files"
         out " clean..:\tremove all the result files"
-        out " clone..:\tclone test1.tpkg to test2.tkpg. TODO wait for better create"
+        out " clone..:\tclone test1.tpkg to test2.tkpg"
         out
         out " When multiple tests are given tkpg will execute each test"
         out " once. Even when there are multilpe depencies to that test."
@@ -139,6 +139,26 @@ function report() {
         echo -e "PASSED: $passed ($pper %)\t\tFAILED: $failed ($fper %)\t\tUNKNOWN: $unknown ($uper %)"
 }
 
+# clone test1 to test2
+function clone() {
+        $0 extract $test1.tpkg
+        
+        if [ ! -d "$test1.dir" ]; then
+                err "[fatal] No $test1.dir directory? Abort."
+                exit 1
+        fi
+        cd $test1.dir
+        for i in $test1.* ; do 
+                ext=`echo $i | sed s/$test1//`
+                if [ ! -z "$ext" ]; then
+                        mv $i $test2$ext
+                fi
+        done
+        cd ..
+        # rename the dir
+        mv $test1.dir $test2.dir
+        $0 create $test2.tpkg
+}
 
 ### Main 
 # either create a tpkg (ie. call shar) or exe (do a test)
@@ -157,6 +177,17 @@ if [ "${goal}" = "report" ]; then
 fi
 if [ "${goal}" = "clean" ]; then
         cleanreport
+        exit 0
+fi
+
+if [ "${goal}" = "clone" ]; then
+        test1=`basename $2 .tpkg`
+        test2=`basename $3 .tpkg`;
+        if [ -z "$test1" -o -z "$test2" ]; then
+                usage
+                exit 0
+        fi
+        clone
         exit 0
 fi
 
@@ -251,6 +282,10 @@ TMPL_EOF
 fi
 
 dir="${testname}.dir"
+if [ -d $dir ]; then 
+        err "[fatal] Directory $dir already exists. Abort."
+        exit 1
+fi
 mkdir $dir
 if [ ! -d $dir ]; then 
         err "[fatal] Failure to create $dir directory. Abort."
@@ -351,7 +386,7 @@ fi
 
 # this enhances the template from above
 ## Post Processing of some of these variables
-# dsc_aux is a comma seperated list of files, max 4 files (TODO)
+# dsc_aux is a comma seperated list of files, max 8 files
 i=$( echo $dsc_aux | awk -F', ?' '{ print $1 "\n" $2 "\n" $3 "\n" $4 "\n" \
 $5 "\n" $6 "\n" $7 "\n" $8 }' )
 dsc_aux_files=($i)
